# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-04 01:48
from __future__ import unicode_literals

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20180504_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentDemo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='file name')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('modify_time', models.DateTimeField(auto_now=True)),
                ('content', mdeditor.fields.MDTextField()),
            ],
        ),
    ]
